# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-15 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wftda_importer', '0003_jam'),
    ]

    operations = [
        migrations.AddField(
            model_name='jam',
            name='players',
            field=models.ManyToManyField(to='wftda_importer.Player'),
        ),
    ]
