# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-18 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wftda_importer', '0005_playertojam'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertojam',
            name='jam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wftda_importer.Jam'),
        ),
        migrations.AddField(
            model_name='playertojam',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wftda_importer.Player'),
        ),
    ]
