# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-19 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wftda_importer', '0007_auto_20160819_0017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jam',
            old_name='player',
            new_name='players',
        ),
    ]
