# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-17 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wftda_importer', '0009_bout'),
    ]

    operations = [
        migrations.AddField(
            model_name='bout',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
