# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-22 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wftda_importer', '0012_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='players',
            field=models.ManyToManyField(to='wftda_importer.Player'),
        ),
    ]
