# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-02 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wftda_importer', '0013_roster_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='jam',
            name='bout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wftda_importer.Bout'),
        ),
        migrations.AlterField(
            model_name='bout',
            name='home_roster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wftda_importer.Roster'),
        ),
    ]
