# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-18 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wftda_importer', '0014_auto_20161002_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='playertojam',
            name='lead_flag',
            field=models.BooleanField(default=False),
        ),
    ]
